create table SS_TRANSACTION (
  ID BIGINT NOT NULL,
  ACCOUNT_ID BIGINT NOT NULL,
  CATEGORY_ID BIGINT NOT NULL,
  DATE TIMESTAMP NOT NULL,
  AMOUNT DECIMAL(9,2) NOT NULL,
  COMMENT VARCHAR(150) NULL,
  IMPORTANT INT NOT NULL
);

create table SS_ACCOUNT (
  ID BIGINT NOT NULL,
  NAME VARCHAR(50) NOT NULL
);

create table SS_CATEGORY (
  ID BIGINT NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  MONTH_LIMIT INT NULL
);

create table SS_MONTH (
  ID BIGINT NOT NULL,
  STARTING DATE NOT NULL,
  STARTING_BAL DECIMAL(9,2) NOT NULL,
  FINISHED INT NULL
);

alter table SS_TRANSACTION add CONSTRAINT PK_TRANSACTION PRIMARY KEY (ID);
alter table SS_ACCOUNT add CONSTRAINT PK_ACCOUNT PRIMARY KEY (ID);
alter table SS_CATEGORY add CONSTRAINT PK_CATEGORY PRIMARY KEY (ID);
alter table SS_MONTH add CONSTRAINT PK_MONTH PRIMARY KEY (ID);


alter table SS_TRANSACTION add CONSTRAINT FK_TRANSACTION_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES SS_ACCOUNT(ID);
alter table SS_TRANSACTION add CONSTRAINT FK_TRANSACTION_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES SS_CATEGORY(ID);
